# Generated by Django 4.1.2 on 2022-11-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_make_product_slug_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
