# Generated by Django 4.1.2 on 2022-11-06 14:41

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.MyUserManager()),
            ],
        ),
    ]
